import { query } from '$app/server';
import type { Book } from '#lib/types/book.js';

type BookSeed = [
	title: string,
	author: string,
	price: number,
	categories: string[],
	description: string
];

const categoryColors: Record<string, string> = {
	'Fiction': '#1e3a8a',
	'Classic': '#7c2d12',
	'Fantasy': '#4c1d95',
	'Science Fiction': '#0e7490',
	'Mystery': '#334155',
	'Thriller': '#7f1d1d',
	'Crime': '#1c1917',
	'Horror': '#18181b',
	'Romance': '#9d174d',
	'Historical': '#78350f',
	'History': '#713f12',
	'Biography': '#3f6212',
	'Memoir': '#166534',
	'Science': '#115e59',
	'Technology': '#1e40af',
	'Programming': '#0f766e',
	'Philosophy': '#57534e',
	'Psychology': '#6b21a8',
	'Self-Help': '#b45309',
	'Business': '#1f2937',
	'Economics': '#374151',
	'Cooking': '#b91c1c',
	'Travel': '#0369a1',
	'Poetry': '#86198f',
	'Children': '#ca8a04',
	'Young Adult': '#c2410c',
	'Adventure': '#15803d'
};

const fallbackColor = '#334155';

const seeds: BookSeed[] = [
	['To Kill a Mockingbird', 'Harper Lee', 14.99, ['Fiction', 'Classic'], 'A young girl confronts racial injustice in the Depression-era South.'],
	['1984', 'George Orwell', 12.99, ['Fiction', 'Science Fiction', 'Classic'], 'A chilling vision of a totalitarian future ruled by surveillance.'],
	['Pride and Prejudice', 'Jane Austen', 9.99, ['Fiction', 'Romance', 'Classic'], 'Wit and misunderstanding shape the courtship of Elizabeth Bennet.'],
	['The Great Gatsby', 'F. Scott Fitzgerald', 11.5, ['Fiction', 'Classic'], 'Jazz-age glamour masks longing and disillusion on Long Island.'],
	['One Hundred Years of Solitude', 'Gabriel García Márquez', 16, ['Fiction', 'Classic'], 'The rise and fall of the Buendía family across generations.'],
	['The Catcher in the Rye', 'J.D. Salinger', 10.99, ['Fiction', 'Classic'], 'A restless teenager wanders New York after leaving prep school.'],
	['Beloved', 'Toni Morrison', 15, ['Fiction', 'Historical', 'Classic'], 'A former enslaved woman is haunted by the ghost of her past.'],
	['The Kite Runner', 'Khaled Hosseini', 13.99, ['Fiction', 'Historical'], 'Friendship and betrayal against the backdrop of a changing Afghanistan.'],
	['Life of Pi', 'Yann Martel', 13, ['Fiction', 'Adventure'], 'A boy survives a shipwreck adrift with a Bengal tiger.'],
	['The Book Thief', 'Markus Zusak', 14.5, ['Fiction', 'Historical', 'Young Adult'], 'Death narrates a girl\'s love of books in Nazi Germany.'],
	['Never Let Me Go', 'Kazuo Ishiguro', 14, ['Fiction', 'Science Fiction'], 'Three friends uncover the quiet horror behind their sheltered school.'],
	['The Road', 'Cormac McCarthy', 13.5, ['Fiction', 'Science Fiction', 'Adventure'], 'A father and son journey across a scorched, post-apocalyptic land.'],
	['The Hobbit', 'J.R.R. Tolkien', 12.99, ['Fantasy', 'Adventure', 'Classic'], 'A comfort-loving hobbit is swept into a quest for dragon gold.'],
	['The Fellowship of the Ring', 'J.R.R. Tolkien', 16.99, ['Fantasy', 'Adventure', 'Classic'], 'A fellowship sets out to destroy a ring of terrible power.'],
	['A Game of Thrones', 'George R.R. Martin', 18, ['Fantasy', 'Adventure'], 'Noble houses scheme and clash for the Iron Throne.'],
	['The Name of the Wind', 'Patrick Rothfuss', 16.5, ['Fantasy', 'Adventure'], 'A legendary magician recounts the making of his own myth.'],
	['Mistborn: The Final Empire', 'Brandon Sanderson', 15.99, ['Fantasy', 'Adventure'], 'A street thief joins a heist to topple an immortal tyrant.'],
	['The Way of Kings', 'Brandon Sanderson', 19.99, ['Fantasy', 'Adventure'], 'On a storm-scoured world, ancient powers begin to stir again.'],
	['The Lion, the Witch and the Wardrobe', 'C.S. Lewis', 8.99, ['Fantasy', 'Children', 'Classic'], 'Four children step through a wardrobe into a frozen kingdom.'],
	['Harry Potter and the Sorcerer\'s Stone', 'J.K. Rowling', 12.99, ['Fantasy', 'Young Adult', 'Children'], 'An orphaned boy discovers he is a wizard bound for a hidden school.'],
	['American Gods', 'Neil Gaiman', 15.5, ['Fantasy', 'Fiction'], 'Old and new gods wage a quiet war across modern America.'],
	['The Night Circus', 'Erin Morgenstern', 14.5, ['Fantasy', 'Romance'], 'Two young illusionists are bound by a magical, lifelong duel.'],
	['Good Omens', 'Terry Pratchett & Neil Gaiman', 13.99, ['Fantasy', 'Fiction'], 'An angel and a demon team up to prevent the apocalypse.'],
	['Dune', 'Frank Herbert', 16.99, ['Science Fiction', 'Adventure', 'Classic'], 'A desert planet\'s spice fuels an epic of prophecy and power.'],
	['Foundation', 'Isaac Asimov', 13.99, ['Science Fiction', 'Classic'], 'A mathematician predicts the fall of a galactic empire.'],
	['Neuromancer', 'William Gibson', 14, ['Science Fiction', 'Classic'], 'A burned-out hacker takes one last job in a neon cyberfuture.'],
	['The Left Hand of Darkness', 'Ursula K. Le Guin', 13.5, ['Science Fiction', 'Classic'], 'An envoy navigates the politics of a genderless alien world.'],
	['Snow Crash', 'Neal Stephenson', 15, ['Science Fiction'], 'A pizza-delivering hacker races a virus through the Metaverse.'],
	['The Three-Body Problem', 'Liu Cixin', 15.99, ['Science Fiction'], 'First contact hinges on a physics puzzle and a doomed civilization.'],
	['Ender\'s Game', 'Orson Scott Card', 12.99, ['Science Fiction', 'Young Adult'], 'A gifted child is trained through games to fight an alien war.'],
	['The Martian', 'Andy Weir', 14.5, ['Science Fiction', 'Adventure'], 'A stranded astronaut science-hacks his way to survival on Mars.'],
	['Project Hail Mary', 'Andy Weir', 16.99, ['Science Fiction', 'Adventure'], 'A lone astronaut wakes with amnesia on a mission to save Earth.'],
	['Do Androids Dream of Electric Sheep?', 'Philip K. Dick', 13, ['Science Fiction', 'Classic'], 'A bounty hunter tracks androids nearly indistinguishable from humans.'],
	['Klara and the Sun', 'Kazuo Ishiguro', 15, ['Science Fiction', 'Fiction'], 'An artificial friend observes love and loneliness with tender eyes.'],
	['The Girl with the Dragon Tattoo', 'Stieg Larsson', 14.99, ['Mystery', 'Thriller', 'Crime'], 'A journalist and a hacker probe a decades-old disappearance.'],
	['Gone Girl', 'Gillian Flynn', 13.99, ['Thriller', 'Mystery', 'Crime'], 'A wife vanishes and a marriage\'s dark secrets unravel.'],
	['The Silent Patient', 'Alex Michaelides', 13.5, ['Thriller', 'Mystery'], 'A therapist obsesses over a woman who shot her husband and went mute.'],
	['The Da Vinci Code', 'Dan Brown', 12.99, ['Thriller', 'Mystery', 'Adventure'], 'A symbologist races through Paris chasing a religious secret.'],
	['And Then There Were None', 'Agatha Christie', 11.99, ['Mystery', 'Crime', 'Classic'], 'Ten strangers are lured to an island and killed one by one.'],
	['The Girl on the Train', 'Paula Hawkins', 13, ['Thriller', 'Mystery'], 'A commuter\'s fixation on a couple pulls her into a disappearance.'],
	['Big Little Lies', 'Liane Moriarty', 13.99, ['Fiction', 'Mystery'], 'Suburban secrets among three mothers build toward a fatal night.'],
	['The Hound of the Baskervilles', 'Arthur Conan Doyle', 9.99, ['Mystery', 'Crime', 'Classic'], 'Holmes and Watson confront a legendary curse on the moors.'],
	['The Talented Mr. Ripley', 'Patricia Highsmith', 13, ['Thriller', 'Crime', 'Classic'], 'A charming con man kills to keep the life he has stolen.'],
	['The Shining', 'Stephen King', 14.99, ['Horror', 'Thriller', 'Classic'], 'A haunted hotel preys on a caretaker and his psychic son.'],
	['It', 'Stephen King', 18.99, ['Horror', 'Thriller'], 'Seven friends reunite to face a shape-shifting evil from childhood.'],
	['Dracula', 'Bram Stoker', 9.99, ['Horror', 'Classic'], 'A count\'s move to England unleashes an ancient vampiric hunger.'],
	['Frankenstein', 'Mary Shelley', 8.99, ['Horror', 'Science Fiction', 'Classic'], 'A scientist\'s creation turns to vengeance against its maker.'],
	['Mexican Gothic', 'Silvia Moreno-Garcia', 14.5, ['Horror', 'Historical'], 'A socialite uncovers rot beneath a decaying countryside mansion.'],
	['Sapiens', 'Yuval Noah Harari', 16.99, ['History', 'Science'], 'A sweeping account of how Homo sapiens came to rule the Earth.'],
	['Guns, Germs, and Steel', 'Jared Diamond', 16, ['History', 'Science'], 'Geography, not race, shaped the fates of human societies.'],
	['The Diary of a Young Girl', 'Anne Frank', 10.99, ['History', 'Biography', 'Classic'], 'A Jewish girl\'s luminous journal from hiding during the Holocaust.'],
	['A People\'s History of the United States', 'Howard Zinn', 18, ['History'], 'American history retold from the perspective of the marginalized.'],
	['The Wright Brothers', 'David McCullough', 15.5, ['History', 'Biography'], 'The dogged inventors who taught the world to fly.'],
	['Team of Rivals', 'Doris Kearns Goodwin', 18.99, ['History', 'Biography'], 'Lincoln forged a cabinet from his fiercest political opponents.'],
	['Steve Jobs', 'Walter Isaacson', 17.99, ['Biography', 'Business', 'Technology'], 'The volatile genius who reinvented computing, music, and phones.'],
	['Einstein: His Life and Universe', 'Walter Isaacson', 17, ['Biography', 'Science'], 'The life of the patent clerk who reimagined space and time.'],
	['Becoming', 'Michelle Obama', 16.99, ['Memoir', 'Biography'], 'The former First Lady traces her path from Chicago to the White House.'],
	['Educated', 'Tara Westover', 15.99, ['Memoir', 'Biography'], 'A woman escapes a survivalist family to pursue an education.'],
	['When Breath Becomes Air', 'Paul Kalanithi', 14.99, ['Memoir', 'Biography'], 'A neurosurgeon confronts mortality after his own terminal diagnosis.'],
	['The Glass Castle', 'Jeannette Walls', 13.99, ['Memoir', 'Biography'], 'A resilient childhood shaped by brilliant, deeply unstable parents.'],
	['Born a Crime', 'Trevor Noah', 15, ['Memoir', 'Biography'], 'Growing up mixed-race and mischievous under apartheid South Africa.'],
	['A Brief History of Time', 'Stephen Hawking', 15, ['Science'], 'A tour of black holes, the Big Bang, and the nature of time.'],
	['Cosmos', 'Carl Sagan', 16, ['Science'], 'A lyrical journey through the universe and our place within it.'],
	['The Selfish Gene', 'Richard Dawkins', 14.5, ['Science'], 'Evolution reframed from the vantage point of the gene.'],
	['The Gene: An Intimate History', 'Siddhartha Mukherjee', 17.5, ['Science', 'History'], 'The story of heredity from Mendel\'s peas to modern genomics.'],
	['The Immortal Life of Henrietta Lacks', 'Rebecca Skloot', 15, ['Science', 'Biography'], 'How one woman\'s cells transformed medicine without her consent.'],
	['Astrophysics for People in a Hurry', 'Neil deGrasse Tyson', 12.99, ['Science'], 'The cosmos, explained in bite-sized, elegant essays.'],
	['Silent Spring', 'Rachel Carson', 14, ['Science', 'History', 'Classic'], 'The landmark warning that launched the environmental movement.'],
	['Meditations', 'Marcus Aurelius', 9.99, ['Philosophy', 'Classic'], 'A Roman emperor\'s private notes on virtue and Stoic calm.'],
	['The Republic', 'Plato', 11.99, ['Philosophy', 'Classic'], 'A foundational dialogue on justice and the ideal society.'],
	['Man\'s Search for Meaning', 'Viktor E. Frankl', 11.5, ['Philosophy', 'Psychology', 'Memoir'], 'A psychiatrist finds purpose amid the horror of the camps.'],
	['Thinking, Fast and Slow', 'Daniel Kahneman', 17, ['Psychology', 'Science'], 'Two systems of thought that drive how we judge and decide.'],
	['The Power of Habit', 'Charles Duhigg', 15, ['Psychology', 'Self-Help', 'Business'], 'Why habits form and how they can be rewired.'],
	['Atomic Habits', 'James Clear', 16.99, ['Self-Help', 'Psychology'], 'Tiny, compounding changes that build remarkable results.'],
	['Quiet', 'Susan Cain', 15.5, ['Psychology', 'Self-Help'], 'The overlooked strengths of introverts in a loud world.'],
	['The Subtle Art of Not Giving a F*ck', 'Mark Manson', 14.99, ['Self-Help'], 'A blunt case for caring less about the wrong things.'],
	['Daring Greatly', 'Brené Brown', 14.5, ['Self-Help', 'Psychology'], 'How vulnerability fuels courage, connection, and growth.'],
	['The Four Agreements', 'Don Miguel Ruiz', 10.99, ['Self-Help', 'Philosophy'], 'Four simple principles for personal freedom and peace.'],
	['Zero to One', 'Peter Thiel', 15, ['Business', 'Technology'], 'Building the future by creating what has never existed.'],
	['The Lean Startup', 'Eric Ries', 16, ['Business', 'Technology'], 'Validated learning as the engine of modern entrepreneurship.'],
	['Good to Great', 'Jim Collins', 17, ['Business'], 'What separates enduring great companies from the merely good.'],
	['Freakonomics', 'Steven D. Levitt & Stephen J. Dubner', 14.99, ['Economics', 'Science'], 'Hidden incentives behind cheating, crime, and everyday life.'],
	['Rich Dad Poor Dad', 'Robert T. Kiyosaki', 13.99, ['Business', 'Self-Help'], 'Two fathers, two mindsets, and lessons about money.'],
	['Capital in the Twenty-First Century', 'Thomas Piketty', 19.99, ['Economics', 'History'], 'A data-driven study of wealth, inequality, and capitalism.'],
	['Thinking in Bets', 'Annie Duke', 14.5, ['Business', 'Psychology'], 'Making smarter decisions when you don\'t have all the facts.'],
	['The Pragmatic Programmer', 'Andrew Hunt & David Thomas', 39.99, ['Programming', 'Technology'], 'Timeless tips and best practices for the modern developer.'],
	['Clean Code', 'Robert C. Martin', 34.5, ['Programming', 'Technology'], 'A handbook of agile craftsmanship and writing readable code.'],
	['Designing Data-Intensive Applications', 'Martin Kleppmann', 49.99, ['Programming', 'Technology'], 'The big ideas behind reliable, scalable, maintainable systems.'],
	['Refactoring', 'Martin Fowler', 44, ['Programming', 'Technology'], 'Improving the design of existing code, one small step at a time.'],
	['Structure and Interpretation of Computer Programs', 'Abelson & Sussman', 54.75, ['Programming', 'Technology', 'Classic'], 'A foundational text on programming and abstraction.'],
	['The Mythical Man-Month', 'Frederick P. Brooks Jr.', 29.95, ['Programming', 'Technology', 'Classic'], 'Essays on software engineering and the perils of scheduling.'],
	['Code', 'Charles Petzold', 29.99, ['Programming', 'Technology', 'Science'], 'How computers work, built up from switches and signals.'],
	['Salt, Fat, Acid, Heat', 'Samin Nosrat', 29.99, ['Cooking'], 'Master four elements and cook well without a recipe.'],
	['The Joy of Cooking', 'Irma S. Rombauer', 24.99, ['Cooking', 'Classic'], 'The comprehensive American kitchen companion, generation after generation.'],
	['In Patagonia', 'Bruce Chatwin', 13.5, ['Travel', 'Adventure', 'Classic'], 'A restless, lyrical ramble to the ends of South America.'],
	['The Sun Also Rises', 'Ernest Hemingway', 12.5, ['Fiction', 'Travel', 'Classic'], 'Expatriates drift through Paris and Spain after the Great War.'],
	['Milk and Honey', 'Rupi Kaur', 12.99, ['Poetry'], 'Spare verse on survival, love, loss, and healing.'],
	['The Waste Land and Other Poems', 'T.S. Eliot', 10.5, ['Poetry', 'Classic'], 'Fragmented modernist masterpieces of a disillusioned age.'],
	['Where the Sidewalk Ends', 'Shel Silverstein', 14.99, ['Poetry', 'Children'], 'Playful, mischievous poems and drawings for all ages.'],
	['Charlotte\'s Web', 'E.B. White', 8.99, ['Children', 'Classic'], 'A clever spider spins a plan to save her friend the pig.']
];

const books: Book[] = seeds.map(([title, author, price, categories, description], index) => ({
	id: String(index + 1),
	title,
	author,
	categories,
	description,
	price,
	coverColor: categoryColors[categories[0]] ?? fallbackColor
}));

export const getBooks = query(() => books);
